# This pipeline is primarily for testing the task definitions. The full pipeline
# for getting started guides is generated.
---
jobs:
- name: image
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      trigger: true
    - get: image-source
      trigger: true
  - aggregate:
    - task: setup
      file: ci/image/setup.yml
      input_mapping:
        source: image-source
      params:
        PUBLIC_KEY: {{public-key}}
        PRIVATE_KEY: {{private-key}}
  - put: base-image
    params:
      build: build/image
- name: mongo-image
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      trigger: true
    - get: image-source
      trigger: true
  - task: setup
    file: ci/image/setup.yml
    input_mapping:
      source: image-source
    params:
      PUBLIC_KEY: {{public-key}}
      PRIVATE_KEY: {{private-key}}
  - put: mongo-base-image
    params:
      build: ci/mongo
- name: maven-test
  plan:
  - aggregate:
    - get: ci
    - get: gs-rest-service
      trigger: true
    - get: base-image
      trigger: true
      passed: [image]
  - task: gs-rest-service-maven
    file: ci/tasks/install.yml
    image: base-image
    input_mapping:
      source: gs-rest-service
- name: gradle-test
  plan:
  - aggregate:
    - get: ci
    - get: gs-rest-service
      trigger: true
    - get: base-image
      trigger: true
      passed: [image]
  - task: gs-rest-service-gradle
    file: ci/tasks/build.yml
    image: base-image
    input_mapping:
      source: gs-rest-service
- name: mongo-maven-test
  plan:
  - aggregate:
    - get: ci
    - get: gs-accessing-data-mongodb
      trigger: true
    - get: mongo-base-image
      trigger: true
      passed: [mongo-image]
  - task: gs-accessing-data-mongodb
    file: ci/mongo/install.yml
    image: mongo-base-image
    input_mapping:
      source: gs-accessing-data-mongodb
- name: mongo-gradle-test
  plan:
  - aggregate:
    - get: ci
    - get: gs-accessing-data-mongodb
      trigger: true
    - get: mongo-base-image
      trigger: true
      passed: [mongo-image]
  - task: gs-accessing-data-mongodb
    file: ci/mongo/build.yml
    image: mongo-base-image
    input_mapping:
      source: gs-accessing-data-mongodb

resources:
- name: gs-rest-service
  type: git
  source:
    uri: https://github.com/spring-guides/gs-rest-service.git

- name: gs-accessing-data-mongodb
  type: git
  source:
    uri: https://github.com/spring-guides/gs-accessing-data-mongodb.git

- name: image-source
  type: git
  source:
    uri: https://github.com/spring-guides/gs-rest-service.git
    paths: [complete/pom.xml, complete/build.gradle]

- name: ci
  type: git
  source:
    uri: https://github.com/dsyer/spring-guides-ci.git
    branch: mongo

- name: base-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: springio/spring-ci-base

- name: mongo-base-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: springio/spring-mongo-base
