# This pipeline is primarily for testing the task definitions. The full pipeline
# for getting started guides is generated.
---
jobs:
- name: image
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      trigger: true
    - get: image-source
      trigger: true
  - aggregate:
    - task: setup
      file: ci/image/setup.yml
      input_mapping:
        source: image-source
      params:
        PUBLIC_KEY: {{public-key}}
        PRIVATE_KEY: {{private-key}}
  - put: base-image
    params:
      build: build/image
- name: rabbit-image
  public: true
  serial: true
  plan:
  - aggregate:
    - get: ci
      trigger: true
    - get: image-source
      trigger: true
  - task: setup
    file: ci/image/setup.yml
    input_mapping:
      source: image-source
    params:
      PUBLIC_KEY: {{public-key}}
      PRIVATE_KEY: {{private-key}}
  - put: rabbit-base-image
    params:
      build: ci/rabbit
- name: maven-test
  plan:
  - aggregate:
    - get: ci
    - get: gs-rest-service
      trigger: true
    - get: base-image
      trigger: true
      passed: [image]
  - task: gs-rest-service-maven
    file: ci/tasks/install.yml
    image: base-image
    input_mapping:
      source: gs-rest-service
- name: gradle-test
  plan:
  - aggregate:
    - get: ci
    - get: gs-rest-service
      trigger: true
    - get: base-image
      trigger: true
      passed: [image]
  - task: gs-rest-service-gradle
    file: ci/tasks/build.yml
    image: base-image
    input_mapping:
      source: gs-rest-service
- name: rabbit-maven-test
  plan:
  - aggregate:
    - get: ci
    - get: gs-messaging-rabbitmq
      trigger: true
    - get: rabbit-base-image
      trigger: true
      passed: [rabbit-image]
  - task: gs-messaging-rabbitmq-maven
    file: ci/rabbit/install.yml
    image: rabbit-base-image
    privileged: true
    input_mapping:
      source: gs-messaging-rabbitmq
- name: rabbit-gradle-test
  plan:
  - aggregate:
    - get: ci
    - get: gs-messaging-rabbitmq
      trigger: true
    - get: rabbit-base-image
      trigger: true
      passed: [rabbit-image]
  - task: gs-messaging-rabbitmq
    file: ci/rabbit/build.yml
    image: rabbit-base-image
    privileged: true
    input_mapping:
      source: gs-messaging-rabbitmq

resources:
- name: gs-rest-service
  type: git
  source:
    uri: https://github.com/spring-guides/gs-rest-service.git

- name: gs-messaging-rabbitmq
  type: git
  source:
    uri: https://github.com/spring-guides/gs-messaging-rabbitmq.git

- name: image-source
  type: git
  source:
    uri: https://github.com/spring-guides/gs-rest-service.git
    paths: [complete/pom.xml, complete/build.gradle]

- name: ci
  type: git
  source:
    uri: https://github.com/dsyer/spring-guides-ci.git
    branch: rabbit

- name: base-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: springio/spring-ci-base

- name: rabbit-base-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: springio/spring-rabbit-base
